# Site
title: chanos-dev
description: Junior Developer
url: https://chanos-dev.github.io
logo: chanos.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/main.jpg           # this image will be shown on homepage's left block
  post-list: images/main.jpg      # this image will be shown on post list page
  default-post: images/main.jpg       # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
github:             chanos-dev
email:              chanos.dev@gmail.com
#google.plus:        username
#twitter:            username
#facebook:           username
stackoverflow:     13534068/chanos
linkedin:          찬호-백-ba53a020b
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              chanos-dev
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username 
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
baekjoon:           chanos
rocketpunch:           chanosdev

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
